import { HardDrive, RefreshCw, WalletCards, Gauge, Bot } from 'lucide-react'

export function fmtBytes(n=0){const x=Number(n)||0;if(x>=1073741824)return `${(x/1073741824).toFixed(x>=10737418240?0:2)} GB`;if(x>=1048576)return `${(x/1048576).toFixed(1)} MB`;if(x>=1024)return `${(x/1024).toFixed(1)} KB`;return `${x} B`}
export function fmtNum(n=0){return new Intl.NumberFormat('id-ID',{maximumFractionDigits:2}).format(Number(n)||0)}
export function normalizeCredits(raw={}){const d=raw?.credits||raw?.data||raw;return{balance:Number(d?.balance??d?.credits??d?.credit_balance??d?.available??0),limit:Number(d?.limit??d?.credit_limit??d?.monthly_limit??0),used:Number(d?.used??d?.spent??d?.usage??0),unit:d?.unit||d?.currency||'credit'}}

export function AccountStats({credits,storage,onRefresh}){const p=Math.min(100,Math.max(0,Number(storage?.percent_used)||0));const remain=credits?.limit?Math.max(0,credits.limit-credits.used):null;return <><div className="stats-head"><h4>Akun & Limit</h4><button onClick={onRefresh}><RefreshCw size={15}/>Refresh</button></div><div className="wallet-grid"><div className="wallet-card"><div><WalletCards/><span>Saldo Axynera</span></div><strong>{credits?fmtNum(credits.balance):'—'}</strong><small>{credits?.unit||'credit'}</small><button disabled>Top Up — segera hadir</button></div><div className="wallet-card"><div><Gauge/><span>Sisa Limit</span></div><strong>{remain===null?'—':fmtNum(remain)}</strong><small>{credits?.limit?`Dipakai ${fmtNum(credits.used)} dari ${fmtNum(credits.limit)}`:'Mengikuti plan akun'}</small></div></div><div className="storage-card"><div className="storage-head"><span><HardDrive/>Axynera Cloud</span><b>{storage?`${fmtBytes(storage.used_bytes)} / ${fmtBytes(storage.limit_bytes)}`:'Memuat…'}</b></div><div className="storage-progress"><i style={{width:`${p}%`}}/></div><small>{storage?`${fmtBytes(storage.remaining_bytes)} tersisa • ${storage.files||0} file • ${p.toFixed(1)}% terpakai`:'Mengambil quota dari /v1/storage'}</small></div></>}

export function ThinkingCard({stage}){return <div className="message assistant thinking-message"><span className="msg-avatar"><Bot/></span><div className="thinking-card"><div className="thinking-head"><span className="thinking-pulse"/><b>Berpikir</b></div><div className="thinking-stage">{stage||'Memproses permintaan'}</div><div className="thinking-bar"><i/></div></div></div>}
