import { HardDrive, RefreshCw, WalletCards, Gauge, Bot, Sparkles, Radio, PencilLine, ChevronDown, CheckCircle2, LoaderCircle } from 'lucide-react'
import { useState } from 'react'
export function fmtBytes(n=0){const x=Number(n)||0;if(x>=1073741824)return`${(x/1073741824).toFixed(x>=10737418240?0:2)} GB`;if(x>=1048576)return`${(x/1048576).toFixed(1)} MB`;if(x>=1024)return`${(x/1024).toFixed(1)} KB`;return`${x} B`}
export function fmtNum(n=0){return new Intl.NumberFormat('id-ID',{maximumFractionDigits:2}).format(Number(n)||0)}
export function normalizeCredits(raw={}){const d=raw?.credits||raw?.data||raw;return{balance:Number(d?.balance??d?.credits??d?.credit_balance??d?.available??0),limit:Number(d?.limit??d?.credit_limit??d?.monthly_limit??0),used:Number(d?.used??d?.spent??d?.usage??0),unit:d?.unit||d?.currency||'credit'}}
export function normalizeStorage(raw={}){const d=raw?.storage||raw?.data||raw,limit=Number(d?.limit_bytes??0),used=Number(d?.used_bytes??0),unlimited=Boolean(d?.unlimited||d?.is_unlimited||d?.limit_unlimited),remaining=unlimited?Infinity:Number(d?.remaining_bytes??Math.max(0,limit-used)),percent=unlimited?0:Number(d?.percent_used??(limit>0?used/limit*100:0));return{...d,limit_bytes:limit,used_bytes:used,remaining_bytes:remaining,percent_used:percent,limit_gb:d?.limit_gb??(limit?limit/1073741824:null),unlimited}}
export function AccountStats({credits,storage,onRefresh}){const s=storage?normalizeStorage(storage):null,p=Math.min(100,Math.max(0,Number(s?.percent_used)||0)),remain=credits?.limit?Math.max(0,credits.limit-credits.used):null,cp=credits?.limit?Math.min(100,Math.max(0,(credits.used/credits.limit)*100)):0;return <><div className="stats-head"><h4>{credits?'Akun & Limit':'Axynera Cloud'}</h4>{onRefresh&&<button onClick={onRefresh}><RefreshCw size={15}/>Refresh</button>}</div>{credits&&<div className="wallet-grid"><div className="wallet-card"><div><WalletCards/><span>Saldo Axynera</span></div><strong>{fmtNum(credits.balance)}</strong><small>{credits.unit||'credit'}</small><button disabled>Top Up — segera hadir</button></div><div className="wallet-card"><div><Gauge/><span>Limit</span></div><strong>{credits.limit?`${fmtNum(credits.used)} / ${fmtNum(credits.limit)}`:'—'}</strong><div className="storage-progress"><i style={{width:`${cp}%`}}/></div><small>{credits.limit?`Dipakai ${fmtNum(credits.used)} • sisa ${fmtNum(remain)} • maksimum ${fmtNum(credits.limit)}`:'Mengikuti plan akun dari server'}</small></div></div>}{storage&&<div className="storage-card"><div className="storage-head"><span><HardDrive/>Axynera Cloud</span><b>{s.unlimited?`${fmtBytes(s.used_bytes)} / Unlimited`:`${fmtBytes(s.used_bytes)} / ${fmtBytes(s.limit_bytes)}`}</b></div><div className="storage-progress"><i style={{width:`${p}%`}}/></div><small>{s.unlimited?`${fmtBytes(s.used_bytes)} terpakai • ${s.files||0} file • quota unlimited`:`${fmtBytes(s.remaining_bytes)} tersisa • ${s.files||0} file • ${p.toFixed(1)}% terpakai`}</small></div>}</>}
function SIcon({label=''}){const s=label.toLowerCase();if(s.includes('hubung')||s.includes('stream'))return<Radio size={15}/>;if(s.includes('respons')||s.includes('jawab'))return<PencilLine size={15}/>;return<Sparkles size={15}/>}
export function ThinkingCard({stage,stages=[]}){const[open,setOpen]=useState(true),current=stage||stages.find(x=>x.state==='active')?.label||'Memproses permintaan';return <div className="message assistant thinking-message"><span className="msg-avatar"><Bot/></span><div className={`thinking-card ${open?'open':''}`}><button type="button" className="thinking-toggle" onClick={()=>setOpen(v=>!v)}><span className="thinking-pulse"/><div><b>Nera sedang bekerja</b><small>{current}</small></div><ChevronDown className="thinking-chevron" size={18}/></button>{open&&<div className="thinking-details">{(stages.length?stages:[{id:'current',label:current,state:'active'}]).map((x,i)=><div className={`thinking-row ${x.state||''}`} key={x.id||i}>{x.state==='done'?<CheckCircle2 size={16}/>:x.state==='active'?<LoaderCircle className="spin" size={16}/>:<SIcon label={x.label}/>}<span>{x.label}</span></div>)}<div className="thinking-note">Status proses ditampilkan tanpa membuka penalaran internal.</div></div>}<div className="thinking-bar"><i/></div></div></div>}
