import { useMemo, useState } from 'react'
import { Bot, ChevronRight, Clock3, Code2, FileText, Folder, Globe2, Home, Image, LogOut, Menu, MessageCircle, Plus, Search, Send, Settings, Sparkles, UserRound, Volume2, WandSparkles } from 'lucide-react'
import { SocialLogin } from '@capgo/capacitor-social-login'
import { loginWithGoogle, getMe, sendChat } from './api.js'

const googleClientId = import.meta.env.VITE_GOOGLE_WEB_CLIENT_ID || ''
const tools = [
  { id:'chat', icon:MessageCircle, title:'Chat', sub:'Tanya apa saja' },
  { id:'search', icon:Globe2, title:'Search', sub:'Cari di web' },
  { id:'vision', icon:Image, title:'Vision', sub:'Analisis gambar' },
  { id:'sandbox', icon:Code2, title:'Sandbox', sub:'Jalankan perintah' },
  { id:'file', icon:FileText, title:'Create File', sub:'Buat file apa saja' },
  { id:'tools', icon:WandSparkles, title:'AI Tools', sub:'Lainnya' },
]

export default function App(){
 const [user,setUser]=useState(null),[page,setPage]=useState('home'),[messages,setMessages]=useState([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[authBusy,setAuthBusy]=useState(false),[error,setError]=useState(''),[sidebarOpen,setSidebarOpen]=useState(false)
 const [prefs,setPrefs]=useState({search:true,vision:true,sandbox:true,history:true,voice:true})
 const firstName=useMemo(()=>user?.name?.split(' ')?.[0]||'Kamu',[user])
 async function loginGoogle(){setError('');if(!googleClientId){setError('Google Client ID belum dikonfigurasi di GitHub Actions.');return}try{setAuthBusy(true);await SocialLogin.initialize({google:{webClientId:googleClientId,mode:'online'}});const login=await SocialLogin.login({provider:'google',options:{scopes:['email','profile'],filterByAuthorizedAccounts:false}});const r=login?.result||{};const googleIdToken=r?.idToken||r?.accessToken?.token||r?.authentication?.idToken;if(!googleIdToken)throw new Error('Google Sign-In tidak mengirim ID token.');await loginWithGoogle(googleIdToken);const me=await getMe();const p=me?.user||r?.profile||r;setUser({name:p?.name||p?.displayName||'Pengguna Nera',email:p?.email||'',image:p?.image||p?.imageUrl||p?.photoUrl||'',plan:p?.plan||'Free',storage:p?.storage||null})}catch(e){setError(e?.message||'Login Google gagal.')}finally{setAuthBusy(false)}}
 async function logout(){try{await SocialLogin.logout({provider:'google'})}catch{}setUser(null);setMessages([]);setPage('home')}
 async function submit(e){e?.preventDefault?.();const text=input.trim();if(!text||busy)return;const next=[...messages,{role:'user',content:text}];setMessages(next);setInput('');setBusy(true);setError('');try{const answer=await sendChat(text);setMessages([...next,{role:'assistant',content:answer}])}catch(e){setError(e?.message||'Tidak dapat menghubungi Nera.')}finally{setBusy(false)}}
 const go=p=>{setPage(p);setSidebarOpen(false)}
 if(!user)return <main className="login-screen"><div className="stars"/><section className="login-content"><div className="nera-logo">N<span>✦</span></div><h1>Nera <em>AI</em></h1><p>Asisten AI cerdas untuk<br/>membantu segala kebutuhanmu.</p><div className="planet"/><button className="google-login" onClick={loginGoogle} disabled={authBusy}><b>G</b>{authBusy?'Menghubungkan...':'Login dengan Google'}</button><small>♢ &nbsp; Aman, cepat, dan nyaman</small>{error&&<div className="error-box">{error}</div>}<footer>Dengan masuk, kamu menyetujui<br/><a>Syarat Layanan</a> & <a>Kebijakan Privasi</a></footer></section></main>
 const nav=[['home',Home,'Home'],['chat',MessageCircle,'Chat'],['tools',WandSparkles,'AI Tools'],['history',Clock3,'History'],['drive',Folder,'Drive'],['settings',Settings,'Settings']]
 return <div className="shell"><aside className={`rail ${sidebarOpen?'open':''}`}><div className="brand-mini">Nera <b>AI</b></div>{nav.map(([id,I,l])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><I/><span>{l}</span></button>)}<div className="pro-card"><b>Nera Pro ✨</b><small>Upgrade untuk fitur lebih lengkap.</small><button>Upgrade</button></div></aside><main className="main"><header><button className="menu" onClick={()=>setSidebarOpen(!sidebarOpen)}><Menu/></button><b>Nera <em>AI</em></b><span className="plan">♛ {user.plan||'Free'}</span>{user.image?<img src={user.image}/>:<UserRound/>}</header>{page==='home'&&<HomePage firstName={firstName} go={go}/>} {page==='chat'&&<ChatPage messages={messages} input={input} setInput={setInput} submit={submit} busy={busy} error={error}/>} {page==='settings'&&<SettingsPage user={user} prefs={prefs} setPrefs={setPrefs} logout={logout}/>} {!['home','chat','settings'].includes(page)&&<section className="placeholder"><Sparkles/><h2>{nav.find(n=>n[0]===page)?.[2]}</h2><p>Modul ini sudah disiapkan untuk integrasi Axynera SDK.</p></section>}<nav className="bottom">{[['home',Home,'Home'],['chat',MessageCircle,'Chat'],['new',Plus,''],['tools',WandSparkles,'AI Tools'],['settings',Settings,'Settings']].map(([id,I,l])=><button key={id} className={page===id?'active':''} onClick={()=>id==='new'?go('chat'):go(id)}><I/><span>{l}</span></button>)}</nav></main></div>
}
function HomePage({firstName,go}){return <section className="home-page"><h1>Hai, <em>{firstName}!</em> 👋</h1><p>Ada yang bisa Nera bantu hari ini?</p><div className="tool-grid">{tools.map(t=><button key={t.id} onClick={()=>go(t.id==='chat'?'chat':t.id)}><t.icon/><b>{t.title}</b><span>{t.sub}</span></button>)}</div><div className="model-card"><span>Model Aktif</span><b>✦ &nbsp; Nera-V4</b><ChevronRight/></div><div className="recent"><h3>Riwayat Terakhir</h3>{['Buatkan landing page modern','Jelaskan konsep React Server Component','Bantu analisis gambar arsitektur'].map((x,i)=><button key={x}><MessageCircle/><span>{x}<small>{i+2} menit yang lalu</small></span><ChevronRight/></button>)}</div></section>}
function ChatPage({messages,input,setInput,submit,busy,error}){return <section className="chat-page"><div className="chat-list">{messages.length?messages.map((m,i)=><div className={`msg ${m.role}`} key={i}>{m.content}</div>):<div className="chat-empty"><Bot/><h2>Mulai chat dengan Nera</h2><p>Tanyakan apa saja.</p></div>}{busy&&<div className="msg assistant">Nera sedang berpikir...</div>}</div>{error&&<div className="error-line">{error}</div>}<form className="chat-compose" onSubmit={submit}><Plus/><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Ketik pesan kamu..."/><button><Send/></button></form></section>}
function SettingsPage({user,prefs,setPrefs,logout}){const toggle=k=>setPrefs({...prefs,[k]:!prefs[k]});return <section className="settings-page"><h2>Pengaturan</h2><div className="profile-card">{user.image?<img src={user.image}/>:<UserRound/>}<div><b>{user.name} <em>{user.plan||'Free'}</em></b><span>{user.email}</span><small>{user.storage?`Storage: ${user.storage}`:'Akun Axynera'}</small></div></div><h4>Preferensi</h4><div className="settings-card">{[['Tema','Gelap'],['Bahasa','Indonesia'],['Model Default','Nera-V4'],['Ukuran Teks','Sedang']].map(x=><button key={x[0]}><span>{x[0]}</span><small>{x[1]}</small><ChevronRight/></button>)}<button><span>Suara Respons</span><Toggle on={prefs.voice} click={()=>toggle('voice')}/></button></div><h4>Fitur</h4><div className="settings-card">{[['search','Aktifkan Search Web'],['vision','Aktifkan Vision'],['sandbox','Aktifkan Sandbox'],['history','Simpan Riwayat Chat']].map(([k,l])=><button key={k}><span>{l}</span><Toggle on={prefs[k]} click={()=>toggle(k)}/></button>)}</div><div className="settings-card"><button><span>Tentang Nera AI</span><ChevronRight/></button><button className="logout" onClick={logout}><LogOut/><span>Keluar</span></button></div><p className="version">Nera AI v0.1.0</p></section>}
function Toggle({on,click}){return <span onClick={e=>{e.stopPropagation();click()}} className={`toggle ${on?'on':''}`}><i/></span>}
