import{useEffect,useMemo,useRef,useState}from'react';import{Bot,ChevronDown,Code2,Folder,Home,LogOut,Menu,MessageCircle,Plus,PlugZap,Send,Settings,Sparkles,Square,UserRound,X}from'lucide-react';import{SocialLogin}from'@capgo/capacitor-social-login';import{appendChat,cancelChat,createChat,getChat,getChats,getCredits,getMe,getStorage,loginWithGoogle,logoutSession,resetChatContext,restoreSession,streamChat}from'./api.js';import{AccountStats,ThinkingCard,normalizeCredits,normalizeStorage,fmtBytes,fmtNum}from'./AccountStats.jsx';import ThinkingMode from'./ThinkingMode.jsx';import MessageContent from'./MessageContent.jsx';import MessageActions from'./MessageActions.jsx';import BackGuard from'./BackGuard.jsx';import UserBadges from'./UserBadges.jsx';import ProfileEditor from'./ProfileEditor.jsx';import QuickEdit from'./QuickEdit.jsx';import ChatAttachment from'./ChatAttachment.jsx';import Connectors from'./Connectors.jsx';import'./account.css';
const gc=import.meta.env.VITE_GOOGLE_WEB_CLIENT_ID||'';
function nu(r={}){const u=r?.user||r,s=String(u?.status||'').toLowerCase(),role=String(u?.role||u?.user_role||u?.account_role||'');return{name:u?.name||'Pengguna Nera',email:u?.email||'',image:u?.image||u?.photoUrl||u?.avatar||'',plan:String(u?.plan||'Free'),role,developer:Boolean(u?.developer||u?.is_developer||u?.developer_mode||role.toLowerCase()==='developer'||role.toLowerCase()==='dev'||role.toLowerCase().includes('developer')),storage:u?.storage?normalizeStorage(u.storage):null,banned:!!(u?.banned||['banned','suspended'].includes(s)),banReason:u?.ban_reason||'Akun dibatasi oleh sistem Axynera.'}}
function quotaLabel(st,u){const s=st||u?.storage;if(!s)return'Memuat quota…';const n=normalizeStorage(s);if(n.unlimited)return'∞';if(n.limit_gb!=null)return`${Number(n.limit_gb).toFixed(Number(n.limit_gb)%1?1:0)} GB`;return fmtBytes(n.limit_bytes)}
function listChats(raw){const d=raw?.chats||raw?.data||raw?.items||raw;return Array.isArray(d)?d:[]}
function chatId(x){return x?.id||x?.chat_id||x?._id||''}
function chatTitle(x){return x?.title||x?.name||x?.preview||'Chat Nera'}
function chatMessages(raw){const d=raw?.messages||raw?.chat?.messages||raw?.data?.messages||raw?.data||[];return Array.isArray(d)?d.filter(x=>x&&typeof x.content==='string').map(x=>({role:x.role||'user',content:x.content})):[]}
export default function AppV2(){
const[boot,setBoot]=useState(true),[u,setU]=useState(null),[p,setP]=useState('home'),[m,setM]=useState([]),[inp,setInp]=useState(''),[attachment,setAttachment]=useState(null),[busy,setBusy]=useState(false),[ab,setAb]=useState(false),[err,setErr]=useState(''),[think,setThink]=useState(''),[stages,setStages]=useState([]),[thinkMode,setThinkMode]=useState('fast'),[cr,setCr]=useState(null),[st,setSt]=useState(null),[side,setSide]=useState(false),[history,setHistory]=useState([]),[activeId,setActiveId]=useState(''),[showDown,setShowDown]=useState(false);
const msgRef=useRef(null),fn=useMemo(()=>u?.name?.split(' ')[0]||'Kamu',[u]);
async function stats(){const[me,c,s,h]=await Promise.allSettled([getMe(),getCredits(),getStorage(),getChats()]);if(me.status==='fulfilled'){const x=nu(me.value);setU(v=>({...v,...x}));if(x.storage)setSt(x.storage)}if(c.status==='fulfilled')setCr(normalizeCredits(c.value));if(s.status==='fulfilled')setSt(normalizeStorage(s.value?.storage||s.value?.data||s.value));if(h.status==='fulfilled')setHistory(listChats(h.value))}
useEffect(()=>{(async()=>{try{const me=await restoreSession();if(me){const x=nu(me);setU(x);if(x.storage)setSt(x.storage);stats()}}finally{setBoot(false)}})()},[]);
useEffect(()=>{const el=msgRef.current;if(!el)return;const near=el.scrollHeight-el.scrollTop-el.clientHeight<180;if(near||busy)requestAnimationFrame(()=>el.scrollTo({top:el.scrollHeight,behavior:'smooth'}))},[m,busy,think,stages]);
async function login(){setErr('');if(!gc)return setErr('Google Client ID belum dikonfigurasi.');try{setAb(true);await SocialLogin.initialize({google:{webClientId:gc,mode:'online'}});const x=await SocialLogin.login({provider:'google',options:{filterByAuthorizedAccounts:false,style:'standard'}}),r=x?.result||{},id=r?.idToken||r?.authentication?.idToken;if(!id)throw Error('Google ID token tidak tersedia.');await loginWithGoogle(id);const me=nu(await getMe());setU(me);if(me.storage)setSt(me.storage);stats()}catch(e){setErr(String(e?.message||e))}finally{setAb(false)}}
async function out(){try{await SocialLogin.logout({provider:'google'})}catch{}await logoutSession();setU(null);setM([]);setCr(null);setSt(null);setHistory([]);setActiveId('')}
async function ensureChat(title){if(activeId)return activeId;try{const c=await createChat(title||'Chat baru');const id=chatId(c?.chat||c?.data||c);if(id)setActiveId(id);return id}catch{return''}}
function pushStage(s){setThink(s.label);setStages(prev=>{const i=prev.findIndex(x=>x.id===s.id);if(i<0)return[...prev,s];const n=[...prev];n[i]={...n[i],...s};return n})}
function modeSystem(){return{role:'system',content:thinkMode==='smart'?'Jawab dengan analisis lebih teliti, pertimbangkan konteks dan akurasi sebelum memberi hasil akhir. Tetap ringkas bila tidak perlu panjang.':'Prioritaskan respons cepat, langsung, jelas, dan efisien tanpa analisis berlebihan.'}}
async function runStream(base,{persistUser=null,title}={}){setBusy(true);setErr('');const modeLabel=thinkMode==='smart'?'Mode Pintar aktif':'Mode Cepat aktif';setThink(modeLabel);setStages([{id:'mode',label:modeLabel,state:'done'}]);setM([...base,{role:'assistant',content:'',streaming:true}]);try{const id=await ensureChat(title||base.findLast?.(x=>x.role==='user')?.content?.slice(0,60)||'Chat baru');if(id&&persistUser)appendChat(id,persistUser,title).catch(()=>{});let latest='';const apiBase=base.map(x=>({role:x.role,content:x.apiContent||x.content}));const a=await streamChat([modeSystem(),...apiBase],{mode:thinkMode==='smart'?'pintar':'cepat',onStage:pushStage,onToken:(_,full)=>{latest=full;setM([...base,{role:'assistant',content:full,streaming:true}])}});const final=a||latest;setM([...base,{role:'assistant',content:final,final:true}]);if(id)appendChat(id,{role:'assistant',content:final}).catch(()=>{});stats()}catch(e){setM(base);if(String(e?.message)!=='REQUEST_CANCELLED')setErr(e?.message||'Gagal menghubungi Nera.')}finally{setBusy(false);setThink('');setStages([])}}
function attachmentContent(t,a){if(!a)return t;if(a.kind==='image')return[{type:'text',text:t||`Jelaskan atau analisis foto ${a.name}.`},{type:'image_url',image_url:{url:a.data}}];if(a.kind==='text')return[{type:'text',text:t||`Analisis file ${a.name}.`},{type:'text',text:`Isi file ${a.name}:\n\n${a.text}`}];return null}
async function submit(e){e?.preventDefault?.();const t=inp.trim();if((!t&&!attachment)||busy)return;if(attachment?.kind==='binary')return setErr('Jenis file ini belum bisa dibaca Nera. Gunakan foto atau file teks/code.');const apiContent=attachmentContent(t,attachment),display=t||(attachment?`📎 ${attachment.name}`:'');const userMsg={role:'user',content:display,...(apiContent&&apiContent!==display?{apiContent}: {})},base=[...m,userMsg];setInp('');setAttachment(null);await runStream(base,{persistUser:{role:'user',content:display},title:m.length?undefined:display.slice(0,60)})}
function editMessage(i){if(busy)return;const x=m[i];if(!x||x.role!=='user')return;setInp(x.content);setM(m.slice(0,i));resetChatContext();requestAnimationFrame(()=>document.querySelector('.composer textarea')?.focus())}
async function regenerate(i){if(busy)return;let ui=i-1;while(ui>=0&&m[ui]?.role!=='user')ui--;if(ui<0)return;const base=m.slice(0,ui+1);resetChatContext();await runStream(base)}
function fresh(){cancelChat();resetChatContext();setM([]);setInp('');setAttachment(null);setErr('');setBusy(false);setThink('');setStages([]);setActiveId('');setP('chat');setSide(false)}
async function openHistory(x){const id=chatId(x);if(!id)return;setErr('');try{const c=await getChat(id);setActiveId(id);setM(chatMessages(c));setP('chat');setSide(false);resetChatContext()}catch(e){setErr(e?.message||'Gagal membuka riwayat chat.')}}
function scrollDown(){const el=msgRef.current;if(el)el.scrollTo({top:el.scrollHeight,behavior:'smooth'})}
const limit=cr?.limit||0,used=cr?.used||0,unlimited=cr?.unlimited||limit===Infinity,remain=unlimited?Infinity:(limit?Math.max(0,limit-used):null),limitPct=unlimited?0:(limit?Math.max(0,Math.min(100,(used/limit)*100)):0);
if(boot)return <main className="login-page"><section className="login-card"><h1>Nera <em>AI</em></h1><p>Memulihkan sesi...</p></section></main>;
if(!u)return <main className="login-page"><div className="login-stars"/><section className="login-card"><div className="logo-box"><span>N</span><Sparkles/></div><h1>Nera <em>AI</em></h1><p>Asisten AI cerdas untuk membantu segala kebutuhanmu.</p><button className="google-btn" onClick={login} disabled={ab}><span className="google-g">G</span>{ab?'Menghubungkan...':'Login dengan Google'}</button>{err&&<div className="error-box">{err}</div>}</section></main>;
if(u.banned)return <main className="banned-page"><section className="banned-card"><h1>Akun ditangguhkan</h1><p>{u.banReason}</p><button className="ban-logout" onClick={out}><LogOut/>Keluar</button></section></main>;
return <div className="shell"><BackGuard side={side} onCloseSide={()=>setSide(false)} page={p} onHome={()=>setP('home')}/>{side&&<button className="side-overlay" aria-label="Tutup sidebar" onClick={()=>setSide(false)}/>}<aside className={`side ${side?'open':''}`}><div className="side-head"><div className="brand"><span className="mini-logo">N</span>Nera <i>AI</i></div><button className="side-close" onClick={()=>setSide(false)}><X size={20}/></button></div><button className="side-new-chat" onClick={fresh}><Plus size={18}/><span>Chat baru</span></button><nav>{[['home',Home,'Home'],['quick',Code2,'Quick Edit'],['chat',MessageCircle,'Chat'],['connectors',PlugZap,'Konektor'],['drive',Folder,'Cloud'],['settings',Settings,'Settings']].map(([id,I,l])=><button key={id} className={p===id?'active':''} onClick={()=>{setP(id);setSide(false);if(!['chat','quick','connectors'].includes(id))stats()}}><I size={18}/><span>{l}</span></button>)}</nav><div className="side-history"><small>RIWAYAT CHAT</small>{history.slice(0,12).map((x,i)=><button key={chatId(x)||i} onClick={()=>openHistory(x)}><MessageCircle size={15}/><span>{chatTitle(x)}</span></button>)}{!history.length&&<p>Belum ada riwayat.</p>}</div></aside><main className="main"><header className="topbar"><button className="menu-btn" onClick={()=>setSide(!side)}><Menu/></button><span className="top-title">Nera <b>AI</b></span><div className="top-actions"><UserBadges user={u}/></div></header>
{p==='home'&&<section className="page home-premium"><div className="hero hero-premium"><div><span className="eyebrow">NERA AI • {u.plan.toUpperCase()}{u.developer?' • DEVELOPER':''}</span><h1>Hai, <span>{fn}!</span> 👋</h1><div style={{marginTop:8}}><UserBadges user={u}/></div><p>Ada yang bisa Nera bantu hari ini?</p></div><button className="new-chat-home" onClick={fresh}><Plus/>Chat baru</button></div><div className="account-overview"><div className="overview-card balance"><small>Saldo Axynera</small><strong>{cr?fmtNum(cr.balance):'—'}</strong><span>{cr?.unit||'credit'}</span></div><div className="overview-card"><small>Limit dipakai</small><strong>{cr?(unlimited?`${fmtNum(used)} / ∞`:limit?`${fmtNum(used)} / ${fmtNum(limit)}`:'—'):'—'}</strong><span>{unlimited?'Tanpa batas maksimum':limit?`${fmtNum(remain)} tersisa`:'Mengikuti plan'}</span><div className="storage-progress"><i style={{width:`${limitPct}%`}}/></div></div><div className="overview-card"><small>Pemakaian Limit</small><strong>{unlimited?'∞':limit?`${limitPct.toFixed(0)}%`:'—'}</strong><span>{unlimited?'Akun Developer':limit?`Maksimum ${fmtNum(limit)}`:'Belum tersedia'}</span></div></div><div className="cloud-mini"><div><Folder/><span><b>Axynera Cloud</b><small>{quotaLabel(st,u)} • {st?`${Math.round(Number(st.percent_used)||0)}% terpakai`:'Memuat penggunaan'}</small></span></div><button onClick={()=>setP('drive')}>Buka Cloud</button></div></section>}
{p==='quick'&&<QuickEdit/>}
{p==='connectors'&&<Connectors/>}
{p==='chat'&&<section className="chat-page chat-polished"><div className="messages" ref={msgRef} onScroll={e=>{const el=e.currentTarget;setShowDown(el.scrollHeight-el.scrollTop-el.clientHeight>220)}}>{m.length?m.map((x,i)=>{if(x.role==='assistant'&&x.streaming&&!x.content)return null;return <div className={`message ${x.role}`} key={i}><span className="msg-avatar">{x.role==='assistant'?<Bot/>:<UserRound/>}</span><div className="message-stack">{x.role==='assistant'&&!x.streaming&&<div className="final-label">Hasil akhir</div>}<div className={`bubble ${x.streaming?'streaming-bubble':''}`}>{x.role==='assistant'?<MessageContent text={x.content} streaming={x.streaming}/>:x.content}</div>{!x.streaming&&<MessageActions role={x.role} text={x.content} disabled={busy} onEdit={()=>editMessage(i)} onRefresh={()=>regenerate(i)}/>}</div></div>}):<div className="empty chat-empty"><div className="nera-orb"><Sparkles/></div><h2>Apa yang ingin kamu kerjakan?</h2><p>Nera siap membantu.</p></div>}{busy&&<ThinkingCard stage={think} stages={stages}/>}</div>{showDown&&<button className="scroll-down" onClick={scrollDown}><ChevronDown/></button>}<div className="composer-wrap">{err&&<div className="error-line">{err}</div>}<ThinkingMode value={thinkMode} onChange={setThinkMode} disabled={busy}/>{attachment&&<div className="attachment-preview-line"><span>{attachment.kind==='image'?'Foto':'File'} • {attachment.name}</span></div>}<form className="composer composer-premium" onSubmit={submit}><ChatAttachment value={attachment} onChange={setAttachment} disabled={busy}/><textarea value={inp} onChange={e=>setInp(e.target.value)} placeholder="Ketik pesan kamu..." disabled={busy}/>{busy?<button type="button" className="send stop-send" onClick={()=>{cancelChat();setThink('Membatalkan proses…')}}><Square size={18} fill="currentColor"/></button>:<button className="send"><Send/></button>}</form></div></section>}
{p==='settings'&&<section className="page settings-page"><div className="settings-title"><h2>Pengaturan</h2></div><div className="profile-card">{u.image?<img src={u.image}/>:<span className="profile-fallback"><UserRound/></span>}<div><h3>{u.name}</h3><UserBadges user={u}/><p>{u.email}</p><small>Cloud plan: {quotaLabel(st,u)}</small></div></div><ProfileEditor user={u} onUpdated={stats}/><div className="settings-group"><h4>Cloud</h4><AccountStats storage={st||u.storage} onRefresh={stats}/></div><div className="settings-group"><h4>Akun</h4><button className="setting-link danger" onClick={out}><LogOut/><span>Keluar</span></button></div></section>}
{p==='drive'&&<section className="page"><div className="hero"><h1>Axynera <span>Cloud</span> ☁️</h1><p>Storage privat milik akunmu • {u.plan} • {quotaLabel(st,u)}</p></div><AccountStats storage={st||u.storage} onRefresh={stats}/></section>}<nav className="bottom-nav"><button className={p==='home'?'active':''} onClick={()=>setP('home')}><Home size={20}/><span>Home</span></button><button className={p==='quick'?'active':''} onClick={()=>setP('quick')}><Code2 size={20}/><span>Quick Edit</span></button><button className={`${p==='chat'?'active':''} nav-plus nav-chat`} onClick={()=>setP('chat')}><MessageCircle size={20}/><span>Chat</span></button><button className={p==='connectors'?'active':''} onClick={()=>setP('connectors')}><PlugZap size={20}/><span>Konektor</span></button><button className={`nav-profile ${p==='settings'?'active':''}`} onClick={()=>{setP('settings');stats()}}>{u.image?<img src={u.image} alt="Profile"/>:<UserRound size={20}/>}<span>Profil</span></button></nav></main></div>}
