import{useState}from'react';import{Check,Copy,Download,ExternalLink,FileText}from'lucide-react';
const linkStyle={display:'inline-flex',alignItems:'center',gap:4,color:'#6d28d9',textDecoration:'none',fontWeight:650};const inlineCodeStyle={fontFamily:'monospace',background:'#f3f7ff',color:'#111827',padding:'2px 6px',border:'1px solid rgba(139,92,246,.16)',borderRadius:6};
const AXY_FILE_RE=/https:\/\/download\.axynera\.my\.id\/f\/[A-Za-z0-9._~%-]+/g;
function niceUrl(url=''){try{const u=new URL(url);return u.hostname.replace(/^www\./,'')+(u.pathname&&u.pathname!=='/'?u.pathname.replace(/\/$/,''):'')}catch{return url}}
function guessFileName(text='',url=''){const before=String(text).slice(0,Math.max(0,String(text).indexOf(url)));const m=before.match(/(?:file|bernama|nama(?: file)?|File)\s*[:“"']?\s*([\w.-]+\.(?:txt|md|html|css|js|json|csv|xml|py|pdf|docx|xlsx|pptx))/i)||before.match(/([\w.-]+\.(?:txt|md|html|css|js|json|csv|xml|py|pdf|docx|xlsx|pptx))\b/i);if(m?.[1])return m[1];try{return decodeURIComponent(new URL(url).pathname.split('/').filter(Boolean).pop()||'File Axynera')}catch{return'File Axynera'}}
function AxyFileCard({url,name}){const[copied,setCopied]=useState(false);async function copy(){try{await navigator.clipboard.writeText(url);setCopied(true);setTimeout(()=>setCopied(false),1400)}catch{}}return <div className="axy-file-card"><div className="axy-file-icon"><FileText size={20}/></div><div className="axy-file-info"><b>{name||'File Axynera'}</b><small>Disimpan di Axynera Cloud</small></div><div className="axy-file-actions"><a href={url} target="_blank" rel="noopener noreferrer" className="axy-file-download"><Download size={15}/>Download</a><button type="button" onClick={copy}>{copied?<Check size={15}/>:<Copy size={15}/>}<span>{copied?'Tersalin':'Salin link'}</span></button></div></div>}
function TextLinks({text=''}){const parts=String(text).split(/(https?:\/\/[^\s<>()]+|\[[^\]]+\]\(https?:\/\/[^\s)]+\))/g).filter(Boolean);return <>{parts.map((p,i)=>{const md=p.match(/^\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)$/);if(md)return <a style={linkStyle} href={md[2]} target="_blank" rel="noopener noreferrer" key={i}>{md[1]}<ExternalLink size={12}/></a>;if(/^https?:\/\//.test(p)){const clean=p.replace(/[.,!?;:]$/,'');const tail=p.slice(clean.length);return <span key={i}><a style={linkStyle} href={clean} target="_blank" rel="noopener noreferrer">{niceUrl(clean)}<ExternalLink size={12}/></a>{tail}</span>}return <span key={i}>{p}</span>})}</>}
function Inline({text=''}){const parts=String(text).split(/(`[^`]+`|\*\*[^*]+\*\*)/g).filter(Boolean);return <>{parts.map((p,i)=>p.startsWith('**')&&p.endsWith('**')?<strong key={i}>{p.slice(2,-2)}</strong>:p.startsWith('`')&&p.endsWith('`')?<code style={inlineCodeStyle} key={i}>{p.slice(1,-1)}</code>:<TextLinks key={i} text={p}/>)}</>}
function CodeBlock({lang='',code=''}){const[copied,setCopied]=useState(false);async function copy(){try{await navigator.clipboard.writeText(code);setCopied(true);setTimeout(()=>setCopied(false),1400)}catch{}}return <div className="nera-code-block" style={{margin:'12px 0',border:'1px solid rgba(139,92,246,.22)',borderRadius:14,overflow:'hidden',background:'#ffffff',boxShadow:'0 8px 24px rgba(139,92,246,.07)'}}><div style={{padding:'10px 12px',display:'flex',alignItems:'center',justifyContent:'space-between',background:'linear-gradient(90deg,#faf7ff,#f3fbff)',color:'#6b7280',fontSize:12,borderBottom:'1px solid rgba(139,92,246,.14)'}}><span>{lang||'code'}</span><button type="button" onClick={copy} style={{display:'flex',alignItems:'center',gap:6,border:0,background:'transparent',color:'#6d28d9'}}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'Tersalin':'Salin'}</button></div><pre style={{margin:0,padding:14,overflow:'auto',whiteSpace:'pre',fontFamily:'monospace',fontSize:12.5,lineHeight:1.6,background:'#fff',color:'#111827'}}><code>{code}</code></pre></div>}
export default function MessageContent({text='',streaming=false}){const src=String(text||'');const files=[...src.matchAll(AXY_FILE_RE)].map(m=>({url:m[0],name:guessFileName(src,m[0])}));const cleaned=src.replace(AXY_FILE_RE,'').replace(/Download:\s*$/gim,'').trimEnd();const nodes=[];const re=/```([^\n`]*)\n([\s\S]*?)```/g;let last=0,m,i=0;while((m=re.exec(cleaned))){if(m.index>last)nodes.push(<Inline key={`t${i++}`} text={cleaned.slice(last,m.index)}/>);nodes.push(<CodeBlock key={`c${i++}`} lang={m[1].trim()} code={m[2].replace(/\n$/,'')}/>);last=re.lastIndex}if(last<cleaned.length)nodes.push(<Inline key={`t${i++}`} text={cleaned.slice(last)}/>);return <div style={{whiteSpace:'pre-wrap',wordBreak:'break-word',lineHeight:1.65,color:'#111827'}}>{nodes}{files.map((f,idx)=><AxyFileCard key={`${f.url}-${idx}`} {...f}/>)}{streaming&&<span className="typing-caret"/>}</div>}
