import{useEffect,useMemo,useState}from'react';import{Code2,Download,Eye,FileCode2,Play,Plus,RotateCcw,Save,Sparkles,Trash2,WandSparkles}from'lucide-react';import{Preferences}from'@capacitor/preferences';import{Capacitor}from'@capacitor/core';import{Directory,Encoding,Filesystem}from'@capacitor/filesystem';import{streamChat}from'./api.js';import'./quick-edit.css';
const KEY='nera_code_project_v3';
const starter=[
{name:'index.html',content:'<main class="card">\n  <h1>Hello NeraCode 👋</h1>\n  <p>Edit project lalu tekan Run.</p>\n  <button id="btn">Klik saya</button>\n</main>'},
{name:'style.css',content:'body{font-family:system-ui;background:#080c12;color:#fff;display:grid;place-items:center;min-height:100vh;margin:0}.card{padding:28px;border:1px solid #7b45ff;border-radius:18px;background:#101725}button{padding:10px 14px;border:0;border-radius:10px;background:#7c41f1;color:white}'},
{name:'app.js',content:"document.querySelector('#btn')?.addEventListener('click',()=>alert('NeraCode berjalan!'))"}
];
const TEXT_EXT=/\.(html?|css|js|jsx|ts|tsx|json|txt|md|php|py|go|java|c|cpp|h|hpp|rs|sh|bash|xml|yml|yaml|sql|env|ini|conf|log)$/i;
function safeScript(s=''){return String(s).replace(/<\/script/gi,'<\\/script')}
function cleanName(v='file.txt'){let n=String(v).trim().replace(/[\\/:*?"<>|]/g,'-').replace(/^\.+/,'');if(!n)n='file.txt';if(!/\.[a-z0-9]+$/i.test(n))n+='.txt';return n.slice(0,100)}
function mime(name){if(/\.html?$/i.test(name))return'text/html';if(/\.css$/i.test(name))return'text/css';if(/\.(js|jsx|ts|tsx)$/i.test(name))return'text/javascript';if(/\.json$/i.test(name))return'application/json';return'text/plain'}
function lang(name=''){const e=name.split('.').pop()?.toLowerCase()||'txt';return({htm:'html',jsx:'javascript',js:'javascript',ts:'typescript',tsx:'typescript',py:'python',rs:'rust',sh:'bash',yml:'yaml'})[e]||e}
function extractJson(text=''){const fenced=String(text).match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1];const src=(fenced||text).trim();const a=src.indexOf('{'),b=src.lastIndexOf('}');if(a<0||b<a)throw Error('Nera tidak mengirim format edit yang valid.');return JSON.parse(src.slice(a,b+1))}
export default function QuickEdit(){
const[files,setFiles]=useState(starter),[active,setActive]=useState('index.html'),[preview,setPreview]=useState(''),[runtimeError,setRuntimeError]=useState(''),[aiReview,setAiReview]=useState(''),[checking,setChecking]=useState(false),[editing,setEditing]=useState(false),[saved,setSaved]=useState(false),[saveInfo,setSaveInfo]=useState('');
const file=files.find(x=>x.name===active)||files[0];
useEffect(()=>{Preferences.get({key:KEY}).then(({value})=>{if(!value)return;try{const p=JSON.parse(value);if(Array.isArray(p?.files)&&p.files.length){setFiles(p.files.filter(x=>x?.name&&typeof x.content==='string'));setActive(p.active||p.files[0].name)}}catch{}})},[]);
const web=useMemo(()=>{const html=files.find(x=>/\.html?$/i.test(x.name))?.content||'',css=files.filter(x=>/\.css$/i.test(x.name)).map(x=>x.content).join('\n'),js=files.filter(x=>/\.(js|jsx|ts|tsx)$/i.test(x.name)).map(x=>x.content).join('\n');return`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style><script>window.onerror=function(message,source,line,col,error){parent.postMessage({type:'neracode-error',message:String(message),line,col,stack:error&&error.stack?String(error.stack):''},'*')};window.onunhandledrejection=function(e){parent.postMessage({type:'neracode-error',message:'Unhandled promise: '+String(e.reason),stack:e.reason&&e.reason.stack?String(e.reason.stack):''},'*')}</script></head><body>${html}<script>${safeScript(js)}<\/script></body></html>`},[files]);
useEffect(()=>{const onMsg=e=>{if(e.data?.type==='neracode-error')setRuntimeError([e.data.message,e.data.line?`baris ${e.data.line}:${e.data.col||0}`:'',e.data.stack||''].filter(Boolean).join('\n'))};window.addEventListener('message',onMsg);return()=>window.removeEventListener('message',onMsg)},[]);
function update(content){setFiles(v=>v.map(x=>x.name===active?{...x,content}:x))}
function addFile(){const raw=prompt('Nama file baru, contoh api.php atau notes.txt','file.txt');if(!raw)return;let name=cleanName(raw);if(files.some(x=>x.name===name)){let i=2;const m=name.match(/^(.*?)(\.[^.]+)$/);while(files.some(x=>x.name===name))name=m?`${m[1]}-${i++}${m[2]}`:`file-${i++}.txt`}setFiles(v=>[...v,{name,content:''}]);setActive(name)}
function removeFile(name){if(files.length<=1)return;const next=files.filter(x=>x.name!==name);setFiles(next);if(active===name)setActive(next[0].name)}
function run(){setRuntimeError('');setAiReview('');setPreview(web)}
async function saveLocal(){await Preferences.set({key:KEY,value:JSON.stringify({files,active})});setSaved(true);setTimeout(()=>setSaved(false),1300)}
function reset(){setFiles(starter);setActive('index.html');setPreview('');setRuntimeError('');setAiReview('');setSaveInfo('')}
async function saveToDevice(){if(!file)return;const name=cleanName(file.name),data=file.content;setSaveInfo('Menyimpan…');if(Capacitor.isNativePlatform()){try{const r=await Filesystem.writeFile({path:`NeraCode/${name}`,data,directory:Directory.Documents,encoding:Encoding.UTF8,recursive:true});setSaveInfo(`Tersimpan • ${r.uri||name}`);return}catch(e){setSaveInfo(`Gagal simpan: ${e?.message||e}`);return}}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:mime(name)}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000);setSaveInfo(`Download ${name} dibuat.`)}
async function askNera(){if(checking||!file)return;setChecking(true);setAiReview('');let out='';try{await streamChat([{role:'system',content:'Kamu adalah NeraCode Reviewer. Periksa file secara teknis. Fokus pada syntax error, bug nyata, security dasar, dan perbaikan paling kecil. Jangan mengarang error.'},{role:'user',content:`Periksa file ${file.name} (${lang(file.name)}).\n\n${file.content}\n\nRuntime error aktual:\n${runtimeError||'Tidak ada error runtime yang tertangkap.'}`}],{mode:'pintar',onToken:(_,full)=>{out=full;setAiReview(full)}});if(!out)setAiReview('Nera tidak mengirim hasil pemeriksaan.')}catch(e){setAiReview(e?.message||'Gagal menghubungi Nera.')}finally{setChecking(false)}}
async function editWithNera(){if(editing||!file)return;const instruction=prompt('Mau Nera ubah apa pada file ini?','Perbaiki error dan rapikan kode tanpa mengubah fungsi utama.');if(!instruction)return;setEditing(true);setAiReview('Nera sedang mengedit file…');let out='';try{await streamChat([{role:'system',content:'Kamu adalah editor kode NeraCode. Balas HANYA JSON valid tanpa komentar dengan bentuk {"name":"nama-file","content":"isi file lengkap setelah diedit","summary":"ringkasan singkat"}. Jangan pakai diff. Pertahankan nama file kecuali memang diminta menggantinya.'},{role:'user',content:`File aktif: ${file.name}\nBahasa: ${lang(file.name)}\nInstruksi: ${instruction}\nRuntime error: ${runtimeError||'tidak ada'}\n\nISI FILE SEKARANG:\n${file.content}`}],{mode:'pintar',onToken:(_,full)=>{out=full}});const data=extractJson(out);if(typeof data.content!=='string')throw Error('Nera tidak mengirim isi file baru.');const newName=cleanName(data.name||file.name);setFiles(v=>v.map(x=>x.name===file.name?{name:newName,content:data.content}:x));setActive(newName);setAiReview(data.summary||'File sudah diedit langsung oleh Nera.');setRuntimeError('');await Preferences.set({key:KEY,value:JSON.stringify({files:files.map(x=>x.name===file.name?{name:newName,content:data.content}:x),active:newName})})}catch(e){setAiReview(e?.message||'Edit Nera gagal.')}finally{setEditing(false)}}
return <section className="page quick-edit-page"><div className="quick-head"><div><span>NERACODE</span><h2><Code2/> NeraCode</h2><p>Editor multi-file dengan Run web, deteksi error, AI reviewer, dan AI editor langsung.</p></div><div className="quick-actions"><button onClick={addFile}><Plus/>File</button><button onClick={reset}><RotateCcw/>Reset</button><button onClick={saveLocal}><Save/>{saved?'Tersimpan':'Simpan Lokal'}</button><button onClick={saveToDevice}><Download/>Simpan ke HP</button><button className="run" onClick={run}><Play/>Run Web</button></div></div>{saveInfo&&<div className="neracode-save-info">{saveInfo}</div>}<div className="file-strip">{files.map(x=><div key={x.name} className={x.name===active?'active':''}><button onClick={()=>setActive(x.name)}><FileCode2/>{x.name}</button>{files.length>1&&<button className="file-x" onClick={()=>removeFile(x.name)} aria-label={`Hapus ${x.name}`}><Trash2/></button>}</div>)}</div><div className="quick-grid"><div className="editor-panel"><div className="panel-title"><Code2/><span>{file?.name}</span><small>{lang(file?.name)}</small></div><textarea spellCheck="false" value={file?.content||''} onChange={e=>update(e.target.value)}/></div><div className="preview-panel"><div className="panel-title"><Eye/>Web Preview</div><iframe title="NeraCode Preview" sandbox="allow-scripts allow-modals" srcDoc={preview||web}/></div></div><div className={`neracode-console ${runtimeError?'has-error':''}`}><div><b>{runtimeError?'Runtime Error':'NeraCode Console'}</b><span className="console-actions"><button onClick={askNera} disabled={checking||editing}><Sparkles/>{checking?'Memeriksa…':'Periksa'}</button><button className="ai-edit" onClick={editWithNera} disabled={checking||editing}><WandSparkles/>{editing?'Mengedit…':'Edit dengan Nera'}</button></span></div><pre>{runtimeError||'Belum ada error runtime yang tertangkap. PHP/Python/Go bisa diedit & dianalisis; Run Web menjalankan HTML/CSS/JS.'}</pre>{aiReview&&<div className="nera-review"><b>Nera</b><p>{aiReview}</p></div>}</div></section>}
