import{useState}from'react';import{BadgeInfo,Brain,ChevronDown,Database,HelpCircle,Info,LockKeyhole,ShieldCheck,Sparkles,UserCog}from'lucide-react';
const APP_VERSION='0.1.0';
function Row({icon:Icon,title,subtitle,open,onClick}){return <button type="button" className={`settings-extra-row ${open?'open':''}`} onClick={onClick}><span className="settings-extra-icon"><Icon size={18}/></span><span className="settings-extra-copy"><b>{title}</b><small>{subtitle}</small></span><ChevronDown size={17} className="settings-extra-chevron"/></button>}
export default function SettingsExtras({user}){const[open,setOpen]=useState('');const toggle=id=>setOpen(v=>v===id?'':id);const plan=String(user?.plan||'Free');const role=user?.developer?'Developer':(user?.role||'User');return <div className="settings-extras"><h4>Pengaturan lainnya</h4><div className="settings-extra-card">
<Row icon={UserCog} title="Akun & Plan" subtitle={`${plan} • ${role}`} open={open==='account'} onClick={()=>toggle('account')}/>{open==='account'&&<div className="settings-extra-panel"><div><span>Plan</span><b>{plan}</b></div><div><span>Role</span><b>{role}</b></div><div><span>Status limit</span><b>{user?.developer?'∞':'Mengikuti plan'}</b></div><p>Plan, role, dan status limit dibaca dari akun Axynera.</p></div>}
<Row icon={Brain} title="Preferensi AI" subtitle="Mode Cepat dan Pintar" open={open==='ai'} onClick={()=>toggle('ai')}/>{open==='ai'&&<div className="settings-extra-panel"><p>Pilihan mode AI tersedia langsung di halaman Chat. Mode Cepat memprioritaskan respons langsung, sedangkan Pintar memberi ruang analisis lebih teliti.</p></div>}
<Row icon={Database} title="Riwayat & Data" subtitle="Chat, cloud, dan data akun" open={open==='data'} onClick={()=>toggle('data')}/>{open==='data'&&<div className="settings-extra-panel"><p>Riwayat chat disimpan per akun Axynera. File Cloud juga terisolasi per user dan mengikuti quota plan.</p></div>}
<Row icon={LockKeyhole} title="Privasi & Keamanan" subtitle="Session dan data sensitif" open={open==='privacy'} onClick={()=>toggle('privacy')}/>{open==='privacy'&&<div className="settings-extra-panel"><div className="security-chip"><ShieldCheck size={16}/>Session akun dilindungi</div><p>Token login, API key, Google token, email sensitif, dan internal user ID tidak dimasukkan ke konteks percakapan Nera.</p></div>}
<Row icon={HelpCircle} title="Bantuan & Feedback" subtitle="Bantuan penggunaan Nera AI" open={open==='help'} onClick={()=>toggle('help')}/>{open==='help'&&<div className="settings-extra-panel"><p>Untuk kendala aplikasi, login, chat, atau Cloud, gunakan kanal dukungan resmi Axynera saat tersedia. Informasi error bisa disalin dari aplikasi agar lebih mudah diperiksa.</p></div>}
<Row icon={Info} title="Tentang Nera AI" subtitle={`Versi ${APP_VERSION}`} open={open==='about'} onClick={()=>toggle('about')}/>{open==='about'&&<div className="settings-extra-panel about-panel"><div className="about-nera-logo"><Sparkles size={22}/></div><h3>Nera AI</h3><p>Asisten AI dari Axynera dengan SSE streaming, activity realtime, history per akun, Cloud, dan account context aman.</p><div><span>Versi aplikasi</span><b>{APP_VERSION}</b></div><div><span>Model default</span><b>Nera-V4</b></div><div><span>Platform</span><b>Axynera</b></div><div className="about-build"><BadgeInfo size={15}/>Build Android • Capacitor</div></div>}
</div></div>}
